// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4uHY6ceO0WLrZ1JXNRnetVCCnTxrAjQ',
    appId: '1:688626481802:web:5638ed6e49b68316838b73',
    messagingSenderId: '688626481802',
    projectId: 'classdiary2',
    authDomain: 'classdiary2.firebaseapp.com',
    storageBucket: 'classdiary2.appspot.com',
    measurementId: 'G-499KSNPCTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1xMNYMEjo5CCQ8IfM_Ub_t99ehaPn1Q',
    appId: '1:688626481802:android:9b98df8f239ea308838b73',
    messagingSenderId: '688626481802',
    projectId: 'classdiary2',
    storageBucket: 'classdiary2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpMHeB4KxOYiU9-2tAS6lea9I7w-Y6bs',
    appId: '1:688626481802:ios:bdf619be462e258f838b73',
    messagingSenderId: '688626481802',
    projectId: 'classdiary2',
    storageBucket: 'classdiary2.appspot.com',
    iosClientId: '688626481802-es0g5ordq3dg7kh1t0g3et6208a2tbim.apps.googleusercontent.com',
    iosBundleId: 'com.underthebluesun.classdiary2',
  );
}
